blank_issues_enabled: true
contact_links:
  - name: Discord
    about: Ask questions on our Discord Server.
    url: https://discord.gg/EUHuJHt
  - name: Documentation
    about: Useful documentation about Feather, its API, and how you can contribute.
    url: https://docs.feather-mod.vercel.app
